FROM ghcr.io/ublue-os/fedora-toolbox:latest

## Add files
COPY box.sh /opt/protonapps/box.sh
COPY install.sh /build/install.sh

## Install packages & cleanup
RUN chmod +x /build/install.sh && \
    /build/install.sh && \
    dnf clean all && \
    rm -rf /build
